/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import java.util.List;
import model.Predmet;
import controller.Controller;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.PredmetModelTable;
import model.OblikNastave;

/**
 *
 * @author mihajlo
 */
public class GlavnaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        OsveziTabelu();

        
    }
    public void OsveziTabelu(){
            List<Predmet> lista = Controller.getInstance().vratiListuPredmetaZaNastavnika();
        PredmetModelTable pmt = new PredmetModelTable(lista);
        jTablePredmet.setModel(pmt);
        
        List<Predmet> listaSvih = Controller.getInstance().vratiListuSvihPredmeta();
        for (Predmet p : lista){
            if(listaSvih.contains(p)){
                listaSvih.remove(p);
            }
        }
            jComboBoxPredmet.setEnabled(!listaSvih.isEmpty());
            jComboBoxOblik.setEnabled(!listaSvih.isEmpty());
            jButtonUnesi.setEnabled(!listaSvih.isEmpty());
       
        DefaultComboBoxModel<Predmet> model = new DefaultComboBoxModel<>(listaSvih.toArray(new Predmet[0]));
        jComboBoxPredmet.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePredmet = new javax.swing.JTable();
        jButtonOblici = new javax.swing.JButton();
        jComboBoxPredmet = new javax.swing.JComboBox<>();
        jComboBoxOblik = new javax.swing.JComboBox<>();
        jButtonUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePredmet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePredmet);

        jButtonOblici.setText("Prikaži oblike za predmet");
        jButtonOblici.addActionListener(this::jButtonObliciActionPerformed);

        jComboBoxOblik.setModel(new DefaultComboBoxModel<OblikNastave>(OblikNastave.values())
        );

        jButtonUnesi.setText("Unesi");
        jButtonUnesi.addActionListener(this::jButtonUnesiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButtonOblici)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxOblik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPredmet, 0, 153, Short.MAX_VALUE)
                    .addComponent(jButtonUnesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jComboBoxPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxOblik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUnesi)))
                .addGap(18, 18, 18)
                .addComponent(jButtonOblici)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObliciActionPerformed
        int selektovaniPredmet = jTablePredmet.getSelectedRow();
        
        if(selektovaniPredmet == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali predmet!!!");
            return;
        
        }
        else{
            List<Predmet> listaPredmeta = ((PredmetModelTable)jTablePredmet.getModel()).getListaPredmeta();
            ObliciNastaveForma onf = new ObliciNastaveForma(listaPredmeta.get(selektovaniPredmet));
            onf.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonObliciActionPerformed

    private void jButtonUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnesiActionPerformed
         boolean uspesno = Controller.getInstance().unesiNovoAngazovanje((Predmet)jComboBoxPredmet.getSelectedItem(), (OblikNastave)jComboBoxOblik.getSelectedItem());
        OsveziTabelu();
        
        if(uspesno){
            JOptionPane.showMessageDialog(this, "USPESNO JE UNETO NOVO ANGAZOVANJE!!!");
        }
        else{
            JOptionPane.showMessageDialog(this, "DESILA SE GREŠKA PRILIKOM UNOSA NOVOG ANGAŽOVANJA");
        }
        
    }//GEN-LAST:event_jButtonUnesiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new GlavnaForma().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOblici;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JComboBox<OblikNastave> jComboBoxOblik;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePredmet;
    // End of variables declaration//GEN-END:variables
}
