/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Korisnik;
import domen.Poruka;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import komunikacija.Komunikacija;
import modeli.PorukaTableModel;
import niti.AzurirajPodatke;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
/**
 *
 * @author mihajlo
 */
public class KlijentskaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KlijentskaForma.class.getName());
    private Korisnik ulogovani;
    private AzurirajPodatke azuriraj;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(Korisnik ulogovani) {
        initComponents();
        this.ulogovani = ulogovani;
        jLabelInfo.setText("Ulogovani korisnik:" + this.ulogovani.toString());
        Komunikacija.getInstance().setKf(this);
        azuriraj = new AzurirajPodatke();
        azuriraj.start();
        osveziPodatke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPoruka = new javax.swing.JTextField();
        cbKorisnik = new javax.swing.JComboBox<>();
        jButtonSvi = new javax.swing.JButton();
        jButtonKorisnik = new javax.swing.JButton();
        jButtonCela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTri = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOstalo = new javax.swing.JTable();
        jButtonPoruke = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Poruka:");

        txtPoruka.setText("jTextField1");

        cbKorisnik.setModel(new DefaultComboBoxModel<Korisnik>(Komunikacija.getInstance().getKorisnici().toArray(new Korisnik[0])));

        jButtonSvi.setText("POSALJI SVIMA");
        jButtonSvi.addActionListener(this::jButtonSviActionPerformed);

        jButtonKorisnik.setText("POSALJI KORISNIKU");
        jButtonKorisnik.addActionListener(this::jButtonKorisnikActionPerformed);

        jButtonCela.setText("PROCITAJ CELU PORUKU");
        jButtonCela.addActionListener(this::jButtonCelaActionPerformed);

        jTableTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTri);

        jLabel2.setText("Poslednje 3:");

        jLabel3.setText("OstalePoruke");

        jTableOstalo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableOstalo);

        jButtonPoruke.setText("PRIKAZI PORUKE OD KORISNIKA");
        jButtonPoruke.addActionListener(this::jButtonPorukeActionPerformed);

        jLabelInfo.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPoruka))
                    .addComponent(jButtonCela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPoruke, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabelInfo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSvi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPoruke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSviActionPerformed
        String poruka = txtPoruka.getText();
        if(poruka.length() > 200 || poruka.isBlank()){
            JOptionPane.showMessageDialog(null, "PORUKA NE SME BITI PRAZNA I NE SME BITI VEĆA OD 200 karaktera");
            return;  
        }
        List<String> mejlovi = new ArrayList<>();
        for(Korisnik k : Komunikacija.getInstance().getKorisnici()){
            mejlovi.add(k.getEmail());
        }
        mejlovi.remove(ulogovani.getEmail());
        Poruka nova = new Poruka(ulogovani.getEmail(), mejlovi, LocalDateTime.now(), poruka);
        Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.SEND, nova));
        ServerskiOdgovor so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
        JOptionPane.showMessageDialog(null, so.getPoruka());
    }//GEN-LAST:event_jButtonSviActionPerformed

    private void jButtonKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKorisnikActionPerformed
        String poruka = txtPoruka.getText();
        if(poruka.length() > 200 || poruka.isBlank()){
            JOptionPane.showMessageDialog(null, "PORUKA NE SME BITI PRAZNA I NE SME BITI VEĆA OD 200 karaktera");
            return;  
        }
        List<String> mejlovi = new ArrayList<>();
        Korisnik cbK = (Korisnik)cbKorisnik.getSelectedItem();
        mejlovi.add(cbK.getEmail());
        Poruka nova = new Poruka(ulogovani.getEmail(), mejlovi, LocalDateTime.now(), poruka);
        Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.SEND, nova));
        ServerskiOdgovor so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
        JOptionPane.showMessageDialog(null, so.getPoruka());
    }//GEN-LAST:event_jButtonKorisnikActionPerformed

    private void jButtonCelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCelaActionPerformed
         int red = jTableTri.getSelectedRow();
         int red2 = jTableOstalo.getSelectedRow();
         
         if(red == -1 && red2 == -1){
                     JOptionPane.showMessageDialog(null, "MORATE IZABRATI RED");
            return;
         }
        if(red != -1){
            Poruka poruka = ((PorukaTableModel)jTableTri.getModel()).getPoruke().get(red);
            if(poruka.getTekst().length() > 20)
                JOptionPane.showMessageDialog(null, poruka.getTekst(), "PORUKA", JOptionPane.DEFAULT_OPTION);
        }
        if(red2 != -1){
            Poruka poruka = ((PorukaTableModel)jTableOstalo.getModel()).getPoruke().get(red2);
            if(poruka.getTekst().length() > 20)
                JOptionPane.showMessageDialog(null, poruka.getTekst(), "PORUKA", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_jButtonCelaActionPerformed

    private void jButtonPorukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorukeActionPerformed
        List<Poruka> odKorisnika = new ArrayList<>();
        Korisnik odabrani = (Korisnik)cbKorisnik.getSelectedItem();
        
        for(Poruka p : Komunikacija.getInstance().getPoruke()){
            for(String s: p.getPrimalacEmail()){
                if(s.equals(ulogovani.getEmail())){
                    if(p.getPosiljalacEmail().equals(odabrani.getEmail()))
                        odKorisnika.add(p);
                }
            
            }
        }
        PorukeForma pF = new PorukeForma(odabrani, odKorisnika);
        pF.setVisible(true);
    }//GEN-LAST:event_jButtonPorukeActionPerformed

    public void osveziPodatke() {
        List<Korisnik> sviKorisnici = Komunikacija.getInstance().getKorisnici();
        List<Korisnik> novi = new ArrayList<>();
        
        // Filtriraj korisnike - ukloni ulogovanog
        for(Korisnik k : sviKorisnici){
            if(!k.getEmail().equals(ulogovani.getEmail())){
                novi.add(k);
            }
        }
        
        if(novi.isEmpty()){
            jButtonKorisnik.setEnabled(false);
            cbKorisnik.setEnabled(false);
            jButtonSvi.setEnabled(false);
            jButtonPoruke.setEnabled(false);
        }
        else{
            cbKorisnik.setModel(new DefaultComboBoxModel<>(novi.toArray(new Korisnik[0])));
            jButtonKorisnik.setEnabled(true);
            cbKorisnik.setEnabled(true);
            jButtonSvi.setEnabled(true);
            jButtonPoruke.setEnabled(true);
        }
        List<Poruka> poruke = new ArrayList<>();
        for(Poruka p : Komunikacija.getInstance().getPoruke()){
            for(String s : p.getPrimalacEmail())
            {
                if(s.equals(ulogovani.getEmail()))
                    poruke.add(p);
            }

        }
        if(poruke.size() <= 3){
            jTableTri.setModel(new PorukaTableModel(poruke));
            jTableOstalo.setModel(new PorukaTableModel(new ArrayList<Poruka>()));
        }
        else
        {
            List<Poruka> prveTri = new ArrayList<>();
            prveTri.add(poruke.get(poruke.size()-1));
            prveTri.add(poruke.get(poruke.size()-2));
            prveTri.add(poruke.get(poruke.size()-3));
            
            List<Poruka> ostalo = new ArrayList<>(poruke.subList(0, poruke.size()-3));
            
            jTableTri.setModel(new PorukaTableModel(prveTri));
            jTableOstalo.setModel(new PorukaTableModel(ostalo));
        }
            
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Korisnik> cbKorisnik;
    private javax.swing.JButton jButtonCela;
    private javax.swing.JButton jButtonKorisnik;
    private javax.swing.JButton jButtonPoruke;
    private javax.swing.JButton jButtonSvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOstalo;
    private javax.swing.JTable jTableTri;
    private javax.swing.JTextField txtPoruka;
    // End of variables declaration//GEN-END:variables
}
