/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Korisnik;
import java.net.SocketException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import niti.DisposeNit;
import niti.PorukeNit;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author student2
 */
public class KlijentskaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KlijentskaForma.class.getName());
    private Korisnik ulogovani = null;
    private DisposeNit dn;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        dn = new DisposeNit();
        dn.setkF(this);
        dn.start();
        Komunikacija.getInstance().setkF(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPosalji = new javax.swing.JButton();
        txtKomanda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonPosalji.setText("Posalji");
        jButtonPosalji.addActionListener(this::jButtonPosaljiActionPerformed);

        txtKomanda.setText("LOGIN petar");

        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKomanda, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPosalji, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(txtKomanda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        String tekst = txtKomanda.getText().trim();
        String[] split = tekst.split(" ");
                if(tekst.isEmpty() || tekst.isBlank()){
            txtKomanda.setText("");
            jTextAreaChat.append(" [ERROR]: NISTE LEPO UNELI KOMANDU!\n");
            return;
        }
        System.out.println(split[0].toUpperCase());
        switch (split[0].toUpperCase()) {
            case "LOGIN":
                if(ulogovani == null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGIN, tekst));
                ServerskiOdgovor so =(ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
                
                if(so.getOdgovor() != null){
                    ulogovani = (Korisnik)so.getOdgovor();
                    Komunikacija.getInstance().getPn().start();
                }else
                    jTextAreaChat.append(so.getPoruka() + "\n");
                }
                else jTextAreaChat.append("[ERROR]: VEĆ STE ULOGOVANI\n"); 
                    
                break;
            case "SEND":
                System.out.println(tekst);
                Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.SEND, tekst));
                break;
            case "BROADCAST":
                Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.BROADCAST, tekst));
                break;
            case "LOGOUT":
                Komunikacija.getInstance().getPn().ugasiNit();
                Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGOUT, "")); 
                ulogovani = null;
                this.dispose();
            default:
                jTextAreaChat.append("\n[ERROR]: UNELI STE NEPOSTOJEĆU KOMANDU\n");
        }
        
        txtKomanda.setText("");
        
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(ulogovani != null)
            Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGOUT, ""));
    }//GEN-LAST:event_formWindowClosing
    public void proveri(int sekunde){
        if(ulogovani == null){
            if(sekunde >= 10)
                this.dispose();
            setTitle("Forma će se ugasiti za: " + (10 - sekunde) + " sekundi ako se ne prijavite!");
        }
        else
            setTitle("Ulogovani ste kao: " + ulogovani.getUsername());
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KlijentskaForma().setVisible(true));
    }

    public void prikaziPoruku(String string) {
        if(string == null || string.isBlank())
            return;
        jTextAreaChat.append("\n" + string);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextField txtKomanda;
    // End of variables declaration//GEN-END:variables
}
