/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Korisnik;
import javax.swing.JOptionPane;
import niti.SekundeNit;
import transfer.KlijentskiZahtev;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.ServerskiOdgovor;
/**
 *
 * @author mihajlo
 */
public class KlijentskaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KlijentskaForma.class.getName());
    SekundeNit sek;
    int sekunde;
    private Korisnik ulogovani = null;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        sek = new SekundeNit(this);
        sek.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKomanda = new javax.swing.JTextField();
        jButtonPosalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelInfo.setText("jLabel1");

        jLabel2.setText("KOMANDA:");

        txtKomanda.setText("LOGIN petar");
        txtKomanda.addActionListener(this::txtKomandaActionPerformed);

        jButtonPosalji.setText("POSALJI");
        jButtonPosalji.addActionListener(this::jButtonPosaljiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKomanda, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addComponent(jButtonPosalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKomanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKomandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKomandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKomandaActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        String tekst = txtKomanda.getText().trim();
        String[] split = tekst.split(" ");
        ServerskiOdgovor so;
        if(tekst.isEmpty() || tekst.isBlank()){
            txtKomanda.setText("");
            JOptionPane.showMessageDialog(null, "NISTE LEPO UNELI KOMANDU");
            return;
        }
        System.out.println(split[0]);
        switch (split[0].toUpperCase()) {
            case "LOGIN":
                if(ulogovani == null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGIN, tekst));
                    so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
                    ulogovani = (Korisnik)so.getOdgovor();
                    JOptionPane.showMessageDialog(null, (String)so.getPoruka());
                }
                else JOptionPane.showMessageDialog(null, "VEĆ STE ULOGOVANI");
                break;
            case "ADD":
                if(ulogovani != null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.ADD, tekst));
                    so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
                    JOptionPane.showMessageDialog(null, (String)so.getPoruka());
                }
                else JOptionPane.showMessageDialog(null, "NISTE ULOGOVANI");
                break;
            case "MINMAX":
                if(ulogovani != null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.MINMAX, tekst));
                    so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
                    JOptionPane.showMessageDialog(null, (String)so.getPoruka());
                }else JOptionPane.showMessageDialog(null, "NISTE ULOGOVANI");
                break;
            case "DATE":
                if(ulogovani != null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.DATE, tekst));
                    so = (ServerskiOdgovor) Komunikacija.getInstance().primiOdgovor();
                    JOptionPane.showMessageDialog(null, (String)so.getPoruka());
                }else JOptionPane.showMessageDialog(null, "NISTE ULOGOVANI");
                break;
            case "LOGOUT":
                if(ulogovani != null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGOUT, tekst));
                    this.dispose();
                }else JOptionPane.showMessageDialog(null, "NISTE ULOGOVANI");
                break;
            default:
                if(ulogovani != null)
                    JOptionPane.showMessageDialog(null, "NISTE LEPO UNELI KOMANDU");
                else JOptionPane.showMessageDialog(null, "NISTE ULOGOVANI");
                
        }
        txtKomanda.setText("");
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(ulogovani != null){
                    Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.LOGOUT, "LOGOUT"));
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KlijentskaForma().setVisible(true));
    }

    public void proveri(int sekunde) {
        if(ulogovani == null){
           if(sekunde == 10)
               this.dispose();
          jLabelInfo.setText("Ako se ne ulogujete, forma se gasi za: " + (10 -sekunde) + " sekundi");
        }
        else{
            jLabelInfo.setText("Ulogovani ste kao: " + ulogovani.getUsername());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JTextField txtKomanda;
    // End of variables declaration//GEN-END:variables
}
